module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    TEACHER: 'TEACHER',
    ASSISTANT: 'ASSISTANT',
    STUDENT: 'STUDENT',
  },

  ATTENDANCE_STATUS: {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LATE: 'LATE',
    EXCUSED: 'EXCUSED',
  },

  VOCABCHECK_STATUS: {
    FOUND: 'FOUND',         // Yodlagan/Topgan
    NOT_FOUND: 'NOT_FOUND', // Topolmagan/Yodlamagan
    PENDING: 'PENDING',     // Hali so'ralmagan
  },

  HOMEWORK_TYPES: {
    URL: 'URL',
    TEXT: 'TEXT',
    VOCABULARY: 'VOCABULARY',
  },

  SUBMISSION_STATUS: {
    PENDING: 'PENDING',
    SUBMITTED: 'SUBMITTED',
    REVIEWED: 'REVIEWED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
  },

  SPEAKING_TEST_STATUS: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
  },

  DAYS_OF_WEEK: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },

  // Role hierarchy: who can create whom
  ROLE_CREATION_PERMISSIONS: {
    ADMIN: ['MANAGER', 'TEACHER', 'ASSISTANT', 'STUDENT'],
    MANAGER: ['TEACHER', 'ASSISTANT', 'STUDENT'],
    TEACHER: ['STUDENT'],
  },
};
